### PR TITLE
Updated to 1.14

### PR DESCRIPTION
**Pull request by tchristofferson**
Changes inside Wrapper1_14_R1 class:

- sendPacketOpenWindow method, replaces the string "minecraft:anvil" with Containers.Anvil and for the chat message part instead of first arg being Blocks.ANVIL.a() it is switched to Blocks.ANVIL.T_()

- setActiveContainer method, the Container windowId field is now final, had to use reflection in order to update the field

- Wrapper1_14_R1.AnvilContainer constructor accepts Player and the ContainerAnvil constructor changed in 1.14

### CODE REVIEW

**Comment by WesJD** [comment]
thanks so much! I'll give it a quick test once I'm at my machine and then merge it.

**Comment by WesJD** [comment]
please rebase your fork to the most recent commit.

**Comment by tchristofferson** [comment]
I resolved the conflicts. Should be fine now.

**Comment by tchristofferson** [comment]
There is an issue when calling getTitle on the InventoryView when anvil gui is open. If I call setTitle in the constructor for AnvilContainer it fixes the issue, however, this way seems hacky. I'm not really sure what to do about it. The error result in the title being null, can find it in net.minecraft.server.v1_14_R1.Container class method getTitle.

**Comment by WesJD** [comment]
to be completely honest, this entire library is "hacky". just do what works.

**Comment by tchristofferson** [comment]
Alright I just added it.

**Comment by js6pak** [comment]
When this will be available on repo? @WesJD

**Comment by WesJD** [comment]
shoot! forgot to deploy. I'll do it this weekend. thanks for your patience.

**Comment by WesJD** [comment]
@js6pak deployed.

**Pull request merged**
