### PR TITLE
Update to mc 1.15

### PR DESCRIPTION
**Pull request by mastercake10**
I've updated the API to support mc 1.15. Tested on git-Spigot-f39a89e-73698cf (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT).

### CODE REVIEW

**Comment by portlek** [comment]
Are test tests done?

**Comment by mastercake10** [comment]
> Are the tests done?

Which tests? The repo does not provide any maven tests. I've just tested it with one of my plugins.

**Comment by portlek** [comment]
I mean plugin test, not maven.

**Comment by WesJD** [comment]
@portlek, @mastercake10 said in the PR message that he had already tested the code.

@mastercake10 We do not increment the version number when adding new Minecraft versions. If you could please revert that commit, that would be great. If not, I can do it this weekend. Thank you for contributing!

**Pull request merged**
