### PR TITLE
Remove plugin Builder method

### PR DESCRIPTION
**Pull request by Osnixer**
Change getting instance from `JavaPlugin#getProvidingPlugin`

### CODE REVIEW

**Comment by portlek** [comment]
what's is the benefit of this?

**Comment by Osnixer** [comment]
Not everyone likes to use instances of the plugin in certain classes and this getting instance automatically.

> what's is the benefit of this?

**Comment by portlek** [comment]
i see that but you are making a breaking change. at least you should annotate them deprecated and old the old codes then add the new ones.

**Comment by WesJD** [comment]
While I like the way you are thinking, in the plugin ecosystem, people typically do not shade their resources. So, the providing plugin could be another plugin that is loaded - not the one initializing the AnvilGUI instance. If this plugin were to unregister all of its listeners, then an AnvilGUI in a your own plugin would break. For sanity, we will keep providing the plugin explicitly. 

Again, thank you for the thought! It is an interesting idea.

**Pull request closed without merging**
