### PR TITLE
Update AnvilGUI.java

### PR DESCRIPTION
**Pull request by Trexon25**
Players are able to add items into the anvil inv with shift + leftclick.
I would rather to cancel the event also in the player inv.

### CODE REVIEW

**Comment by portlek** [comment]
Did you test that?

**Comment by Trexon25** [comment]
Yeah I did test that. A you see in the screenshot the event will only be canceled when you click a slot in 
the anvil. anvil_slots
(https://www.spigotmc.org/threads/anvil-slots.153020/)

anvil

**Comment by WesJD** [comment]
It would be better to fix this by handling the shift click correctly. Blocking all movement in the inventory can have unintended consequences on other servers.

**Comment by Trexon25** [comment]
Yeah I thought about that. But its possible to put an item into the anvil without shift as in the GIF demonstrated. Maybe its possible to disable moving items between the two inventories with InventoryMoveItemEvent.

**Comment by portlek** [comment]
It can be add to the builder as a method such like `builder.lockPlayerInventory()`

**Comment by WesJD** [comment]
@portlek that still wouldn't solve the issue properly. Not making players able to move anything != fixing shift clicking correctly.

I can take a look at this later in the week if you don't get a chance to figure it out @Trexon25.

**Comment by Trexon25** [comment]
@WesJD I will take a look this evening.

**Comment by Trexon25** [comment]
_new commit added_

I came up with this solution. Sometimes it's slightly buggy. I think it's because the server is to "slow" to cancel the event before the players adds the item to the anvil inv.

**Comment by Phoenix616** [comment]
`InventoryAction.COLLECT_TO_CURSOR` should probably also get blocked so that items can't be pulled out of the inventory.

**Comment by WesJD** [comment]
@Phoenix616 if you could, please submit a separate PR for that addition. I appreciate your help.

**Pull request merged**
