### PR TITLE
1.19.2 Support

### PR DESCRIPTION
**Pull request by Peter-Crawley**
#226 won't work, this will *probably*, and it is a lot simpler.

### CODE REVIEW

**Comment by WesJD** [comment]
Probably? Have you fully tested it?

**Comment by Peter-Crawley** [comment]
Assuming the VersionMatcher picks Wrapper1_19_R1 it will work, the work around I mentioned is running on my server and working fine.

I'm not all that sure how to go about testing it properly.

**Comment by Peter-Crawley** [comment]
The versioned package of CraftBukkit hasn't changed so it is still `v1_19_R1`, so based on that it *should* work, at least if I am interpreting how the VersionMatcher works correctly.

**Comment by WesJD** [comment]
Yeah should be good then.

**Pull request merged**
