### PR TITLE
Update AnvilGUI.java

### PR DESCRIPTION
**Pull request by Darrionat**
Remove unnecessary field change

### CODE REVIEW

**Comment by WesJD** [comment]
Do you care to explain your changes? This makes no sense. The open boolean should represent the open state. You've now made it not reflect that.

**Comment by Darrionat** [comment]
`        if (!open) {
            return;
        }

        open = false;`
This is the code. I removed `open=false` because you already know it's false due to the previous if statement.

**Comment by WesJD** [comment]
It isn't false. It's true to pass that if statement.

**Comment by Darrionat** [comment]
I was just about to close this once I recognized my mistake. You're correct.

**Pull request closed without merging**
