### PR TITLE
Added support for 1.19.4

### PR DESCRIPTION
**Pull request by KarmaDeb**
The way that has been achieved is not the best one, but until md_5 releases spigot 1.19.4 in BuildTools that's what we've got

### CODE REVIEW

**Comment by WesJD** [comment]
So is 1.19.4 in the CodeMC NMS repo yet? If not, I will leave this PR open until it is and for people who need support, they can build this PR. Only doing this because the CI pipeline needs it to be in the CodeMC NMS repo.

**Comment by 0dinD** [comment]
No, not yet. Someone already asked for it on their Discord server:

https://discord.com/channels/405915656039694336/782998254945959966/1085986153817182290

I don't know who's responsible, but I would assume we just have to wait patiently.

**Comment by KarmaDeb** [comment]
> So is 1.19.4 in the CodeMC NMS repo yet? If not, I will leave this PR open until it is and for people who need support, they can build this PR. Only doing this because the CI pipeline needs it to be in the CodeMC NMS repo.

I know it's late (at least here is 2:26 PM) but 1.19.4 is yet in the [CodeMC NMS repo](https://repo.codemc.io/#browse/browse:nms:org%2Fspigotmc%2Fspigot%2F1.19.4-R0.1-SNAPSHOT)

**Comment by WesJD** [comment]
Thanks for your work here. Had another PR and accepted that one - they were identical :). Closing this PR.

**Pull request closed without merging**
